def find_order(g, n):           #计算元素g在群Zn中的阶
    for k in range(1, n + 1):
        if (g * k) % n == 0:
            return k
    return n
def generate_subgroup(g, n):    #生成元素g在群Zn中的子群
    order = find_order(g, n)
    subgroup = set((g * i) % n for i in range(order))
    return subgroup
def main():
    n = 30    #群Z30
    subgroups = {}
    for g in range(n):          #遍历每个可能的元素来找到所有子群
        subgroup = generate_subgroup(g, n)
        subgroups[frozenset(subgroup)] = g
    for subgroup, generator in subgroups.items():    #输出
        print(f"Subgroup generated by {generator}: {sorted(subgroup)}")
if __name__ == "__main__":
    main()