#!/usr/bin/env python3
"""Rebuild the locally bundled web fonts in assets/fonts/.

The book used to load its fonts from Google Fonts, which fails offline and is
unreliable in mainland China. This script produces the self-hosted copy:

  * Inter, Playfair Display and DM Mono: the woff2 files Google Fonts serves,
    downloaded unmodified, keeping only the unicode subsets the book uses.
  * Noto Serif SC: subset from the upstream variable font to the characters
    that appear in the book's HTML files (about 1,500), so the file stays small.

Run it again after adding text with new Chinese characters:

    python3 -m pip install fonttools brotli
    python3 tools/build_fonts.py            # downloads fonts (needs network)
    python3 tools/build_fonts.py --noto-only path/to/NotoSerifSC[wght].ttf

Requires network access unless --noto-only is given with a local TTF.
"""
import argparse
import glob
import html
import os
import re
import sys
import tempfile
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "fonts")
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/141.0 Safari/537.36")

GOOGLE_CSS = ("https://fonts.googleapis.com/css2"
              "?family=Playfair+Display:ital,wght@0,400..700;1,400..700"
              "&family=Inter:wght@300..600"
              "&family=DM+Mono:wght@400;500"
              "&display=swap")
KEEP_SUBSETS = {"latin", "latin-ext", "greek"}
NOTO_TTF_URL = ("https://raw.githubusercontent.com/google/fonts/main/"
                "ofl/notoserifsc/NotoSerifSC%5Bwght%5D.ttf")
NOTO_WOFF2 = "noto-serif-sc-subset.woff2"
FONT_ORDER = ["Inter", "Playfair Display", "DM Mono"]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read()


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def book_chars():
    """Every character in the book's HTML, including \\uXXXX escapes in JS."""
    chars = set(chr(c) for c in range(0x20, 0x7F))
    for path in glob.glob(os.path.join(ROOT, "*.html")):
        text = html.unescape(open(path, encoding="utf-8").read())
        chars |= set(text)
        for m in re.findall(r"\\u([0-9a-fA-F]{4})", text):
            chars.add(chr(int(m, 16)))
    return {c for c in chars if ord(c) >= 0x20}


def build_latin():
    css = fetch(GOOGLE_CSS).decode()
    faces = []
    for m in re.finditer(r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", css, re.S):
        subset, body = m.groups()
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", body).group(1)
        style = re.search(r"font-style: (\w+)", body).group(1)
        weight = re.search(r"font-weight: ([^;]+);", body).group(1)
        url = re.search(r"src: url\(([^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range: ([^;]+);", body).group(1)
        name = f"{slug(family)}-{style}-{slug(weight)}-{subset}.woff2"
        with open(os.path.join(OUT, name), "wb") as f:
            f.write(fetch(url))
        faces.append((FONT_ORDER.index(family), family, style, weight, subset,
                      name, urange))
    return sorted(faces)


def build_noto(ttf):
    from fontTools import subset

    chars = book_chars()
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False,
                                     encoding="utf-8") as f:
        f.write("".join(sorted(chars)))
        text_file = f.name
    subset.main([
        ttf,
        f"--text-file={text_file}",
        "--flavor=woff2",
        "--layout-features=*",
        "--no-hinting",
        "--desubroutinize",
        f"--output-file={os.path.join(OUT, NOTO_WOFF2)}",
    ])
    os.unlink(text_file)
    return len(chars)


def write_css(faces):
    out = [
        "/* Self-hosted web fonts, generated by tools/build_fonts.py.",
        " * Licenses: assets/fonts/LICENSES/ (SIL Open Font License 1.1). */",
        "",
    ]
    for _, family, style, weight, subset, name, urange in faces:
        out += [
            f"/* {family} {style}, {subset} (unmodified Google Fonts file) */",
            "@font-face {",
            f"  font-family: '{family}';",
            f"  font-style: {style};",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url({name}) format('woff2');",
            f"  unicode-range: {urange};",
            "}",
        ]
    out += [
        "/* Noto Serif SC, variable weight, subset to the characters in the book */",
        "@font-face {",
        "  font-family: 'Noto Serif SC';",
        "  font-style: normal;",
        "  font-weight: 200 900;",
        "  font-display: swap;",
        f"  src: url({NOTO_WOFF2}) format('woff2');",
        "}",
        "",
    ]
    with open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--noto-only", metavar="TTF",
                    help="only re-subset Noto Serif SC from this local TTF")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)

    if args.noto_only:
        n = build_noto(args.noto_only)
        print(f"Subset Noto Serif SC to {n} characters")
        return

    for old in glob.glob(os.path.join(OUT, "*.woff2")):
        os.unlink(old)
    faces = build_latin()
    with tempfile.TemporaryDirectory() as tmp:
        ttf = os.path.join(tmp, "NotoSerifSC.ttf")
        with open(ttf, "wb") as f:
            f.write(fetch(NOTO_TTF_URL))
        n = build_noto(ttf)
    write_css(faces)
    print(f"Wrote {len(faces)} Latin/Greek faces and Noto Serif SC "
          f"({n} characters) to {os.path.relpath(OUT, ROOT)}/")


if __name__ == "__main__":
    sys.exit(main())
